id: I4EDEDFF8
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-05-27T20:25:29.241552'
last_modified: '2022-05-27T20:25:29.241573'
parser: null
source_metadata:
  title: Tārānamaskāraikaviṃśatistotra
  language: sa
  base:
    f256D:
      title: Complete text
      base_file: f256D.txt
      order: 1
  chapter_to_tile: {}
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
